### ISSUE TITLE
点击用户名输入时闪退

### ISSUE THREAD

**Issue by Clickyin** [yang991178/fluent-reader-lite#1]
红米K20Pro  
系统版本:Miui 12.5  21.19
安卓版本:Android11

错误日志:
java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAnimation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:11445)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7504)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7510)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7510)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7510)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7510)
	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:106)
	at android.view.InsetsController.lambda$new$2$InsetsController(InsetsController.java:575)
	at android.view.-$$Lambda$InsetsController$zpmOxHfTFV_3me2u3C8YaXSUauQ.run(Unknown Source:2)
	at android.view.InsetsController.scheduleApplyChangeInsets(InsetsController.java:1361)
	at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:186)
	at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:170)
	at android.view.InsetsController$InternalAnimationControlListener.lambda$onReady$0$InsetsController$InternalAnimationControlListener(InsetsController.java:332)
	at android.view.-$$Lambda$InsetsController$InternalAnimationControlListener$SInf91MjJKDQFXwrp7C-HBi0xaQ.onAnimationUpdate(Unknown Source:13)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
	at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java:349)
	at android.view.InsetsController.lambda$startAnimation$6$InsetsController(InsetsController.java:1344)
	at android.view.-$$Lambda$InsetsController$VzAUS17blucBK1u6-37NlEpdYqI.run(Unknown Source:12)
	at android.view.ViewRootInsetsControllerHost$1.onPreDraw(ViewRootInsetsControllerHost.java:67)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2065)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8497)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
	at android.view.Choreographer.doFrame(Choreographer.java:826)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by yang991178** [comment]
系统？设备？

**Comment by SkadiShieh** [comment]
> 系统？设备？
已经加上了

**Comment by yang991178** [comment]
看起来像flutter/flutter#66232
目前为了避免在国内验证let's encrypt证书时主线程阻塞用的是beta版本，也许可以尝试上面issue里面的解决方法

**Comment by yang991178** [comment]
1.0.0(2)版本应该解决了这个问题
